### ISSUE TITLE
Roadmap for central server legacy mode

### ISSUE THREAD

**Issue by benjaoming** [fle-internal/ka-lite-central#297]
Long-term road map:

Will try to chunk this up into several steps that can be split into individual PRs and solved over time.

The work should take place on Keep.

The gamble is that we will have no desires to deploy something on the old branches and test this on Keep while work is on-going.

- [ ] Turn differences and conflicts into configurable options
- [ ] Merge back into 0.17.x such that no central server branch exists
- [ ] Create a new pre-release with central server configurations implemented
- [ ] Use ka-lite as a dependency from PyPi
- [ ] Test on Globe
- [ ] Delete central-server branch and deploy on Keep
